### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by ltlombardi** [bkobilansky/GenerateSwiftInit#1]
A little instructions on how to install?
thanks😀

**Comment by bkobilansky** [comment]
README included.

I don't have a clean second machine to test the included Mac app on, so let me know if there are other issues.

**Comment by ltlombardi** [comment]
The included app didn't work on my mac. I'm running 10.11.6

Tried to build the app. I run the GenerateSwiftInit target and updated code signing information. A small Windows showed up, like the one attached. Don't know what to do with it.

I tried to copy the GenerateSwiftInit.app in the Finder and paste it in the /Applications folder, and then went to System Preferences > Extensions , but it didn't showed up. 

Don't know what to do next. :-(

![screenshot 2016-11-18 16 50 57](https://cloud.githubusercontent.com/assets/898124/20442292/4bb38324-adaf-11e6-972d-f943aa2f6663.png)

**Comment by bkobilansky** [comment]
On 10.11.x, there is an additional step involving `xpccachectl` and a system restart. Take a look at [this overview](http://www.russbishop.net/xcode-extensions), it might be helpful. You might also want to take a look at other extensions, like [SwiftFormat](https://github.com/nicklockwood/SwiftFormat).

Having said that, I have no plans to support 10.11.x on this project. I'd welcome a PR if you can figure out how to fix this, but I'm already running 10.12 and don't have hardware to debug on.

**Comment by ltlombardi** [comment]
I tried a lot, but couldn't make it work. Tried other extensions also. Gave up, and installed OS X 10.12 Sierra. Now it works
